apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: apache-secret
  
spec:
  provider: aws
  secretObjects:
    - secretName: apache-secret
      type: Opaque
      data:
        - objectName: APACHE_SECRET_WORKING
          key: APACHE_SECRET_WORKING
  parameters:
    objects: |
        - objectName: "APACHE_SECRET_WORKING"
          objectType: "ssmparameter"
          objectAlias: APACHE_SECRET_WORKING
          pathTranslation: False