# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: [33m╷[0m[0m
[33m│[0m [0m[1m[33mWarning: [0m[0m[1mNo outputs found[0m
[33m│[0m [0m
[33m│[0m [0m[0mThe state file either has no outputs defined, or all the defined outputs are empty. Please define an output in your configuration with the
[33m│[0m [0m`output` keyword and run `terraform refresh` for it to become available. If you are using interpolation, please verify the interpolated value
[33m│[0m [0mis not empty. You can use the `terraform console` command to assist.
[33m╵[0m[0m
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "nginx"

env:
  - name: test
    value: temp

secret_env:
  - name: SECRET_MANAGER_WORKING
    aws_secret: TESTING

csi_volume:
  name: secrets-store-inline
  driver: secrets-store.csi.k8s.io
  readOnly: true
  secretProviderClassName: "application-secret-provider"
  mountPath: "/mnt/"
podAnnotations:
  reloader.stakater.com/auto: "true"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: example.charts.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
