apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret
  
spec:
  provider: aws
  secretObjects:
    - secretName: secret
      type: Opaque
      data:
        - objectName: SECRET_MANAGER_WORKING
          key: SECRET_MANAGER_WORKING
parameters:
    objects: |
        - objectName: "SECRET_MANAGER_WORKING"
          objectType: "ssmparameter"
          objectAlias: SECRET_MANAGER_WORKING
          pathTranslation: False